Output test logs to relay's tmpdir, + subtle bug fix
If the spawned node script threw an error (which we wouldn't expect), the error message could be something like:

```
console.lg(<EXPECTED OUTPUT>);
        ^

TypeError: console.lg is not a function
    at [eval]:1:9
    at ...
```

Because the error message quotes verbatim the line that contains <EXPECTED OUTPUT>, our test would pass, even if the script inside failed somehow. Therefore, exact match instead of regex match

Signed-off-by: Rafael Sofi-zada <rafa.sofizadeh@gmail.com>